// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUUl3742g52U4DWN1PGrkJup9WPiy7Aww',
    appId: '1:1192241498:web:913f6a5b6f398724a96b63',
    messagingSenderId: '1192241498',
    projectId: 'quickstartsnohe',
    authDomain: 'quickstartsnohe.firebaseapp.com',
    databaseURL: 'https://quickstartsnohe-default-rtdb.firebaseio.com',
    storageBucket: 'quickstartsnohe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5xb5LiiepAzq1TEvgf0HnrGsilXdJ2E',
    appId: '1:1192241498:android:c946ea876ddc79e4a96b63',
    messagingSenderId: '1192241498',
    projectId: 'quickstartsnohe',
    databaseURL: 'https://quickstartsnohe-default-rtdb.firebaseio.com',
    storageBucket: 'quickstartsnohe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8dt59PrsXQZj-VdtaM4Fxl4Q22ijOEFg',
    appId: '1:1192241498:ios:fd97faa08b8c64ada96b63',
    messagingSenderId: '1192241498',
    projectId: 'quickstartsnohe',
    databaseURL: 'https://quickstartsnohe-default-rtdb.firebaseio.com',
    storageBucket: 'quickstartsnohe.appspot.com',
    androidClientId: '1192241498-6kppc6nuj8hvvnnoeqmhl7o0mtghutq1.apps.googleusercontent.com',
    iosClientId: '1192241498-scu02bkhi02mv2aqi5nknb11vogcvs8q.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.authenticationQuickstart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8dt59PrsXQZj-VdtaM4Fxl4Q22ijOEFg',
    appId: '1:1192241498:ios:fd97faa08b8c64ada96b63',
    messagingSenderId: '1192241498',
    projectId: 'quickstartsnohe',
    databaseURL: 'https://quickstartsnohe-default-rtdb.firebaseio.com',
    storageBucket: 'quickstartsnohe.appspot.com',
    androidClientId: '1192241498-6kppc6nuj8hvvnnoeqmhl7o0mtghutq1.apps.googleusercontent.com',
    iosClientId: '1192241498-scu02bkhi02mv2aqi5nknb11vogcvs8q.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.authenticationQuickstart',
  );
}
