// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8VCwBMvvfKAqnXC5vxBvgEmEISz1N5XA',
    appId: '1:905001072058:web:e25193a00a843ca7801983',
    messagingSenderId: '905001072058',
    projectId: 'ctflutterquickstart',
    authDomain: 'ctflutterquickstart.firebaseapp.com',
    storageBucket: 'ctflutterquickstart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYHWDZI-VYzraflj-GJ9Yj-5vKdqd1uE',
    appId: '1:905001072058:android:6b4d615e68771837801983',
    messagingSenderId: '905001072058',
    projectId: 'ctflutterquickstart',
    storageBucket: 'ctflutterquickstart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv_n3A1NBMCZCE3ic60VQKLal61QZ0_jo',
    appId: '1:993083111617:ios:5e141d4618cfea7367bc40',
    messagingSenderId: '993083111617',
    projectId: 'friendlyeats-flutter-68d79',
    storageBucket: 'friendlyeats-flutter-68d79.appspot.com',
    iosClientId:
        '993083111617-a9q0thbihk8tl0487gfem1hm1ahaieab.apps.googleusercontent.com',
    iosBundleId: 'friendlyeats.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv_n3A1NBMCZCE3ic60VQKLal61QZ0_jo',
    appId: '1:993083111617:ios:1b694b280561da1567bc40',
    messagingSenderId: '993083111617',
    projectId: 'friendlyeats-flutter-68d79',
    storageBucket: 'friendlyeats-flutter-68d79.appspot.com',
    iosClientId:
        '993083111617-lh0dmnumalopnegi244kmfm2o0brl7dg.apps.googleusercontent.com',
    iosBundleId: 'friendlyears.example.app',
  );
}
