// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0QFQQ_e4TQv6mzRe6QjE5H4pvlsuRSI',
    appId: '1:474248463284:web:c6676b8628d2086297e8e1',
    messagingSenderId: '474248463284',
    projectId: 'vertex-ai-devrel',
    authDomain: 'vertex-ai-devrel.firebaseapp.com',
    storageBucket: 'vertex-ai-devrel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxNnSTRdHJ1bo0paLyjulOV6CbzSecaCQ',
    appId: '1:474248463284:android:23f58dd553f5331f97e8e1',
    messagingSenderId: '474248463284',
    projectId: 'vertex-ai-devrel',
    storageBucket: 'vertex-ai-devrel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpBD_g5f6lX72JnnPfke9MeWqr8SMEysg',
    appId: '1:474248463284:ios:1bee535bf196651197e8e1',
    messagingSenderId: '474248463284',
    projectId: 'vertex-ai-devrel',
    storageBucket: 'vertex-ai-devrel.appspot.com',
    iosBundleId: 'com.example.dataconnect',
  );
}
