// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvwnt4nGz92hTDQ7eyvj-IByd9PT2xwU',
    appId: '1:879683392852:web:bdf53dec2d0d242a5324c1',
    messagingSenderId: '879683392852',
    projectId: 'quickstart-flutter',
    authDomain: 'quickstart-flutter.firebaseapp.com',
    storageBucket: 'quickstart-flutter.appspot.com',
    measurementId: 'G-VZRVEJTBVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzkyFBzx4TtwBXeVxZ8Ti1ffRi4xCPMgw',
    appId: '1:879683392852:android:37f06f6541119d535324c1',
    messagingSenderId: '879683392852',
    projectId: 'quickstart-flutter',
    storageBucket: 'quickstart-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSxSJDnw5IaZGb17-qO-nHs0oKsAtydY',
    appId: '1:879683392852:ios:69487cdce83c6afd5324c1',
    messagingSenderId: '879683392852',
    projectId: 'quickstart-flutter',
    storageBucket: 'quickstart-flutter.appspot.com',
    iosClientId: '879683392852-arqv0j1u86mv4v23aq4iq9fkmijakgr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteConfig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiSxSJDnw5IaZGb17-qO-nHs0oKsAtydY',
    appId: '1:879683392852:ios:69487cdce83c6afd5324c1',
    messagingSenderId: '879683392852',
    projectId: 'quickstart-flutter',
    storageBucket: 'quickstart-flutter.appspot.com',
    iosClientId: '879683392852-arqv0j1u86mv4v23aq4iq9fkmijakgr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteConfig',
  );
}
