name: Run CI tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
    - "authentication/**"
    - "crashlytics/**"
    - "firestore/**"
    - "remote_config/**"
    - "storage/**"
    - ".github/workflows"
  push:
    paths-ignore:
    - "**.md"
  workflow_dispatch:

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - name: "Git Checkout"
      uses: actions/checkout@v4
    - name: "Install Flutter"
      run: |
        sh .github/workflows/scripts/install-flutter.sh stable