name: Run CI tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - name: "Install Flutter"
      run: |
        sh .github/workflows/scripts/install-flutter.sh stable