name: Tag Diff

on:
  pull_request:
    
jobs:
  tag-diff:
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
      - name: "Diff tags"
        uses: invertase/quickstart-tag-differ@v0.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
